### ISSUE TITLE
Mutex cannot return a mutable pointer

### ISSUE THREAD

**Issue by uzytkownik** [rust-embedded/cortex-m#359] opened 2021-10-28 02:09 UTC
Currently Mutex implementation in cortex-m returns a normal references instead of mutable one. FWIW bare_metal (used by rtic for example) returns mutable reference and is more full-featured (it may be worthwhile to use it to provide interoperability).

**Comment by TDHolmes** [comment] 2021-12-15 20:51
Seems like a dupe of #224

**Comment by newAM** [comment] 2024-06-30 19:44
I'm triaging Cortex-M issues today, this seems like a duplicate of #224 so I'm going to close it; feel free to re-open if I missed anything!

**Closed by newAM** 2024-06-30 19:44 UTC
Labels: duplicate
